sonar.projectKey=agendi
sonar.projectName=Agendi
sonar.sourceEncoding=UTF-8

sonar.sources=src,scripts
sonar.tests=src
sonar.test.inclusions=**/*.test.*,**/*.spec.*,**/tests/**
sonar.exclusions=**/*.test.*,**/*.spec.*,**/tests/**,**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.coverage.exclusions=scripts/**
sonar.qualitygate.wait=true
